### ISSUE TITLE
Update to distorm-3.5

### ISSUE THREAD

**Issue by Antiever** [gdabah/distormx#2]
In distorm.h we have
`/* diStorm 3.4.2 */`
so looks like it's based on old engine version.
How about update it?

Also there is one more question.
Compiled distorm lib size is  **83**Kb / **78**Kb (x64 / x86)
Compiled distromx lib size is **545**Kb / **533**Kb  (x64 / x86)
Same compiler options used, hooks code is pretty small, so why so huge size?

**Comment by gdabah** [comment]
Yes, I have to update it. Hopefully on the weekend.

Probably some bad compilation flags with debug??
That's weird indeed. Will take a look.

**Comment by Antiever** [comment]
Thank you very much!

As for the size, I also thought that the built-in distorm project is compiled with debug information, but it is **not** configured separately.

It may be more convenient to include it with @ link to the original repository.
In general, it would be even more convenient if distorm linked as a (compiled) _.lib_ file(s), kind of

```
#include "../distorm3/include/distorm.h"
#ifdef _M_IX86
#pragma comment (lib, "distorm_x86.lib")
#else
#pragma comment (lib, "distorm_amd64.lib")
#endif
```

**Comment by gdabah** [comment]
@Antiever Just updated the version manually though.
Anyway, yeah I compile it inline to keep things easier, any objection?
Thanks
